<?php ob_start(); ?>
<!DOCTYPE html>
<html lang = 'ru'>
    <head>
        <meta http-equiv = "cache-control" content = "max-age=0">
        <meta http-equiv = "cache-control" content = "no-cache">
        <meta http-equiv = "expires" content = "0">
        <meta http-equiv = "expires" content = "Tue, 01 Jan 1980 1:00:00 GMT">
        <meta http-equiv = "pragma" content = "no-cache">
        <meta charset = "UTF-8">
        <link rel = "stylesheet" type="text/css" href = "layout/layout.css">
        <script>
            $(document).ready(function () {
                setInterval(function () {
                    cache_clear();
                }, 300000);
            });
            function cache_clear()
            {
                window.location.reload(true);
            }
        </script>
        <title>Отдел Связи и Телекоммуникаций</title>
    </head>
    <body>
        <div class = "top_panel">
            <b>Пользователь: </b><?php echo $_COOKIE["username"]; ?>
            <a href="./auth/logout.php">Выход</a>
            <div class="top_menu">
                <a href=".">Главная</a>
                <a href="?page=requests">Журнал заявок</a>
                <?php if ($_COOKIE["admin"] == 1): ?>
                    <a href="?page=hosts">Сервера</a><!-- меню админа -->
                <?php endif; ?>
            </div>
            <?php if ($_COOKIE["admin"] == 1): ?>
                <a href="../phpmyadmin/" target="_blank">pma</a><!-- phpmyadmin -->
            <?php endif; ?>
        </div>
        <table class="container">
            <tr>
                <td>
                    <div align="center">
                        <div class="container">
                            <?php require $template; ?>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
		<?php
			echo $_SERVER['HTTP_USER_AGENT'];
			echo '<br>';
			echo get_user_os();
		?>
    </body>
</html>
<?php ob_flush(); ?>
